name: cla-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python=3.9
  - jupyter-book
  - jupyterlab
  - numpy
  - xarray
  - dask
  - intake
  - intake-esm
  - pandas
  - ipython
  - pip
  - pip:
      - sphinx-pythia-theme
