name: cla-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python>=3.9
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - xarray
  - dask
  - intake
  - intake-esm
  - pandas
  - ipython
  - s3fs
  - cmaps
  - cartopy
  - pip
  - pip:
      - sphinx-pythia-theme
