name: cla-cookbook-dev
channels:
  - conda-forge
dependencies:
  - python<3.12
  - jupyter-book
  - jupyterlab
  - matplotlib
  - numpy
  - xarray
  - dask
  - intake
  - intake-esm
  - pandas
  - ipython
  - s3fs
  - cmaps
  - cartopy
  - zarr
  - mystmd
