name: nightly-build

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0' # Weekly Sunday at 00:00

jobs:
  build:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: cookbook-dev
      binder_nb_timeout: 3600 # one hour run time

  link-check:
    if: ${{ github.repository_owner == 'ProjectPythia' }}
    uses: ProjectPythia/cookbook-actions/.github/workflows/link-checker.yaml@main
