name: publish-book

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/build-book.yaml@main
    with:
      environment_name: cookbook-dev

  deploy:
    needs: build
    uses: ProjectPythiaCookbooks/cookbook-actions/.github/workflows/deploy-book.yaml@main

