name: trigger-book-build
on:
  pull_request:

jobs:
  build:
    uses: brian-rose/cookbook-actions/.github/workflows/build-book.yaml@timeout
    with:
      environment_name: cookbook-dev
      artifact_name: book-zip-${{ github.event.number }}
